# Generated by Django 3.1.2 on 2020-10-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=255)),
                ('body_type', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
            ],
        ),
    ]
